# Generated by Django 5.2 on 2025-04-07 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_academy_basics_blog_service_skill_delete_resume'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill_2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=40)),
                ('percent', models.IntegerField(default=0)),
            ],
        ),
    ]
