# Generated by Django 5.2 on 2025-04-15 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_skill_2'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='skill_2',
            options={'verbose_name_plural': 'Skills_2'},
        ),
    ]
