# Generated by Django 5.2 on 2025-04-18 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_certificate_delete_blog'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='featured_image',
            field=models.ImageField(blank=True, upload_to='photos/certificates'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='title',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
