# Generated by Django 5.2 on 2025-04-18 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_certificate_featured_image_alter_certificate_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='link',
            field=models.URLField(blank=True),
        ),
    ]
