# Generated by Django 5.2 on 2025-04-18 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_project_delete_service_remove_certificate_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='date',
            field=models.TextField(blank=True),
        ),
    ]
