# Generated by Django 5.2 on 2025-04-26 20:45

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_certificate_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Information',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.IntegerField(default=0)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('linkedin', models.URLField(blank=True)),
                ('github', models.URLField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Informations',
            },
        ),
        migrations.AlterField(
            model_name='certificate',
            name='date',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
    ]
