# Generated by Django 5.2 on 2025-04-26 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_information_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='information',
            name='email',
            field=models.URLField(blank=True),
        ),
    ]
