# Generated by Django 5.2 on 2025-04-26 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_alter_information_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='information',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
