# Generated by Django 5.2 on 2025-05-06 14:11

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_alter_information_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='basics',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
    ]
