# Generated by Django 5.2 on 2025-05-06 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_basics_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basics',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
